### ISSUE TITLE
Core连接成功，但是发消息没有任何反应

### ISSUE THREAD

**Issue by kita-bocchi** [RemKeeper/GSUID_Utils_ZeroBot#1]
![c611c4d399461a2720d3dd843d1adfd4](https://github.com/user-attachments/assets/9c7c6909-f148-44f3-afe0-3ad14ada6a1a)
![2f715ee7a933ed342f0e37d88e610ca8](https://github.com/user-attachments/assets/d4825836-e7e5-4903-8e08-8f7d7a1adbe9)

这是我的配置
{
   "CoreUrl": "ws://127.0.0.1:6700/zerobot",
   "CommandPrefix": "",
   "SuperUsers": [64238XXXX],
   "ConnectGoIsClient": true,
   "ConnectGoCqUrl": "ws://127.0.0.1:6700",
   "ConnectWaitn": 16,
   "ConnectGoCqAccToken": ""
 }
 
 发送安装指令  core安装插件zzzerouid  机器人没有反应，原本的功能正常使用
 
 操作系统Windows
 LLOneBot+zerobot-plugin
 
 请问是哪里出了问题

**Comment by RemKeeper** [comment]
啊？我这个不是zbp的插件啊？你发哪个号上了，你Core设置自己为SuperUser了吗

**Comment by kita-bocchi** [comment]
> 啊？我这个不是zbp的插件啊？你发哪个号上了，你Core设置自己为SuperUser了吗

zbp不能用吗，好吧，我设置了superuser为我自己的QQ号了，在群聊和私聊中给机器人发送指令的

**Comment by RemKeeper** [comment]
我这个是单独作为一个bot端存在的，和zbp在一个层级
